#!/usr/bin/env python3
"""Fail when a change carries the trace of the tool that wrote it rather than the person.

`AGENTS.md` says commits are authored by the person who wrote them and nobody else, and
lists what that rules out: a Co-Authored-By trailer naming an assistant, a tool
attribution, a "generated by" line. Nothing enforced it. A person can leave one of those
in by habit — an editor's default commit template, a paste that kept the footer a tool
printed — and nothing before this said so until a reviewer happened to read the diff.

What is checked, over a commit range, a branch name and a pull request's title and body:

- a Co-authored-by trailer naming a coding assistant rather than a person
- a "generated with" or "generated by" footer naming a coding assistant, including the
  markdown-link footer form ("generated with [Claude Code](...)")
- a session link or a `<Tool>-Session:` trailer pointing at one
- a branch name prefixed for a tool rather than for the change it makes — `claude/`,
  `codex/`, `copilot/`, `ai/` or `bot/` — which is attribution's concern because it names
  who wrote the change rather than what it does. Whether the rest of the name matches
  `<type>/<short-kebab-description>` is a naming-convention question, not an attribution
  one, and belongs to `scripts/check_naming.py` instead: this file's `branch_problem`
  no longer judges the shape, only the tool-named prefix.
- a commit author or committer whose name or email names a coding assistant

`dependabot[bot]`, `github-actions[bot]` and, as a committer, `GitHub
<noreply@github.com>` are expected identities and never flagged; a Co-authored-by naming
a person is exactly what that trailer is for and is left alone. The tool names and the
phrases built around them are assembled from fragments rather than written out whole, so
that a script whose entire purpose is finding this text does not itself become a copy of
it sitting in the tree.

This needs a commit range to mean anything — the default, `origin/main..HEAD`, is a
pull request's own commits against the branch it targets — so it is not part of
`make catalogue`, which runs with nothing but the working tree. `.github/workflows/ci.yml`
supplies the range, the head branch and the pull request's title and body as a job on
every pull request; `make attribution` reproduces it locally against `origin/main`.

Standard library only, like the checks it sits beside. It shells out to `git log`, the
only way to read commit trailers, authors and committers without a third-party library,
resolved to an absolute path exactly as `check_shell.py` resolves `bash`.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# Six coding-assistant names, each split into two fragments so this file — whose entire
# job is recognising this text — does not itself read as a copy of it. `grep` for any one
# of these words over this source finds nothing; the check still finds everything, because
# the fragments are joined before they ever reach a regular expression.
_TOOL_NAMES = (
    "cla" + "ude",
    "cod" + "ex",
    "cop" + "ilot",
    "curs" + "or",
    "gemi" + "ni",
    "chat" + "gpt",
)
_TOOL_ALTERNATION = "|".join(re.escape(name) for name in _TOOL_NAMES)
TOOL_RE = re.compile(rf"\b(?:{_TOOL_ALTERNATION})\b", re.IGNORECASE)

CO_AUTHORED_RE = re.compile(r"^co-authored-by:\s*(.+)$", re.IGNORECASE)
SESSION_TRAILER_RE = re.compile(rf"^(?:{_TOOL_ALTERNATION})-session:\s*\S+", re.IGNORECASE)
# "generated with" / "generated by", the shape of the footer a tool prints under its own
# commits. Built from the same two fragments the constraint this script honours names as
# its example. Matched on its own this fires on ordinary engineering prose — "recording
# lives in tests/fixtures/block_scalars.json now, generated by a" is real text from this
# repository's own history, and "generated by terraform-docs" is real text from a real
# pull request — so `scan_text` below requires a tool name (`TOOL_RE`) to follow the
# phrase on the same line before it counts. That also covers the markdown-link footer
# form, "generated with [Claude Code](https://...)", since the tool name still follows.
_GENERATED = "gener" + "ated"
GENERATED_RE = re.compile(rf"\b{_GENERATED}\s+(?:with|by)\b", re.IGNORECASE)
# The hosted session form: a link under the assistant's own domain, whose second path
# segment is what a footer or a pasted session reference both use. Matches the bare
# footer link and a session-specific one under it alike.
_SESSION_DOMAIN = "clau" + "de.ai"
_SESSION_PATH = "cod" + "e"
SESSION_URL_RE = re.compile(
    rf"https?://{re.escape(_SESSION_DOMAIN)}/{_SESSION_PATH}(?:/\S*)?", re.IGNORECASE
)

# A branch named for the tool that made the change rather than the change itself.
# `dependabot/` is Dependabot's own convention and is exempt — it is not a coding
# assistant's branch and AGENTS.md's rule is about who wrote the change, not what
# automation proposed a version bump. Checked before the prefixes below, so it is an
# explicit allowance rather than something that merely happens not to collide with them
# today: none of the current prefixes match "dependabot/" either, but the check is
# written to name the exemption rather than lean on that being permanent.
_BRANCH_PREFIXES = (
    "cla" + "ude/",
    "ai/",
    "bot/",
    "cod" + "ex/",
    "cop" + "ilot/",
)
_ALLOWED_BRANCH_PREFIX = "dependabot/"

# Branch names this check never judges against the tool-prefix list below. `make attribution`
# (see `Makefile`) sets GITHUB_HEAD_REF to `git rev-parse --abbrev-ref HEAD` before
# calling this script, precisely so the local run really reproduces the branch check
# rather than skipping it by leaving the variable unset — which means the checkout it
# sees really can be "main", a fork's default branch named "master" instead, or the
# literal string "HEAD" that `git rev-parse --abbrev-ref` prints for a detached checkout.
# None of those is ever a pull request's own head branch, so none should fail a check
# whose target is the name proposed for one.
_EXEMPT_BRANCH_NAMES = {"main", "master", "HEAD"}

# Identities every commit here is allowed to carry without being read as an assistant's
# own: the two bot accounts, matched by name, and GitHub's committer identity used when
# a merge is made through the API rather than by a person's own client. `identity_problem`
# checks these first and returns before ever reaching the `TOOL_RE` search, so this is
# explicit documentation of expected identities and a guard against a future change to
# the tool patterns, rather than dead code — today none of these three names contain any
# of the six tool names either, so nothing here currently depends on the check firing to
# stay green. Neither bot name is itself a coding-assistant name, so unlike the tool
# names above there is nothing here worth splitting into fragments.
_ALLOWED_IDENTITY_NAMES = {"dependabot[bot]", "github-actions[bot]"}
_ALLOWED_COMMITTER_NAME = "GitHub"
_ALLOWED_COMMITTER_EMAIL = "noreply@github.com"

RECORD_SEP = "\x1e"
FIELD_SEP = "\x1f"
LOG_FORMAT = FIELD_SEP.join(["%H", "%an", "%ae", "%cn", "%ce", "%B"]) + RECORD_SEP


def git_binary() -> str | None:
    """The absolute path to git, or None. Never a bare name, the way `bash` is resolved
    in `check_shell.py`: a partial path is resolved against whatever PATH holds right
    now, and an absolute one is not."""
    return shutil.which("git")


def scan_text(source: str, text: str) -> list[str]:
    """Every attribution problem in one block of text, described for `::error::`."""
    if not text:
        return []
    problems = []
    for line in text.splitlines():
        stripped = line.strip()
        co_authored = CO_AUTHORED_RE.match(stripped)
        if co_authored and TOOL_RE.search(co_authored.group(1)):
            problems.append(f"{source}: Co-authored-by trailer names a coding tool — {stripped}")
        elif SESSION_TRAILER_RE.match(stripped):
            problems.append(f"{source}: a tool session trailer — {stripped}")
        generated = GENERATED_RE.search(line)
        if generated and TOOL_RE.search(line[generated.end() :]):
            problems.append(f"{source}: a generated-with/by footer — {stripped}")
        if SESSION_URL_RE.search(line):
            problems.append(f"{source}: an assistant session link — {stripped}")
    return problems


def branch_problem(branch: str | None) -> str | None:
    """None, or why a branch name carries the tool that wrote it rather than the change.

    The `<type>/<short-kebab-description>` shape is a separate, naming-convention
    question — `scripts/check_naming.py`'s own `branch_problem` judges that — so this
    one only ever returns the tool-prefix message or None.
    """
    if not branch:
        return None
    if branch in _EXEMPT_BRANCH_NAMES:
        return None
    if branch.startswith(_ALLOWED_BRANCH_PREFIX):
        return None
    for prefix in _BRANCH_PREFIXES:
        if branch.startswith(prefix):
            return f"branch `{branch}` starts with the tool-named prefix `{prefix}`"
    return None


def identity_problem(role: str, name: str, email: str) -> str | None:
    """None, or why a commit's author or committer is not an allowed identity."""
    if name in _ALLOWED_IDENTITY_NAMES:
        return None
    is_github_committer = name == _ALLOWED_COMMITTER_NAME and email == _ALLOWED_COMMITTER_EMAIL
    if role == "committer" and is_github_committer:
        return None
    if TOOL_RE.search(name) or TOOL_RE.search(email):
        return f"{role} `{name} <{email}>` names a coding tool"
    return None


CommitRecord = tuple[str, str, str, str, str, str]


def commits_in(root: Path, commit_range: str, git: str) -> list[CommitRecord]:
    """Every commit in the range, as (hash, author name, author email, committer name,
    committer email, full message)."""
    result = subprocess.run(  # noqa: S603 - absolute path, fixed argv, range is the only variable
        [git, "log", commit_range, f"--format={LOG_FORMAT}"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise ValueError(result.stderr.strip() or f"git log {commit_range} failed")
    records = [r for r in result.stdout.split(RECORD_SEP) if r.strip("\n")]
    commits = []
    for record in records:
        fields = record.lstrip("\n").split(FIELD_SEP, 5)
        if len(fields) != 6:
            continue
        commits.append(tuple(fields))
    return commits


def check(
    root: Path,
    commit_range: str,
    *,
    branch: str | None = None,
    pr_title: str | None = None,
    pr_body: str | None = None,
) -> int:
    git = git_binary()
    if git is None:
        print("git is not on PATH, so nothing was checked", file=sys.stderr)
        return 2

    try:
        commits = commits_in(root, commit_range, git)
    except ValueError as error:
        print(f"::error::could not read commits in range {commit_range} — {error}")
        return 2

    problems: list[str] = []
    for commit_hash, author_name, author_email, committer_name, committer_email, message in commits:
        short = commit_hash[:12]
        problems.extend(scan_text(f"commit {short}", message))
        author_bad = identity_problem("author", author_name, author_email)
        if author_bad:
            problems.append(f"commit {short}: {author_bad}")
        committer_bad = identity_problem("committer", committer_name, committer_email)
        if committer_bad:
            problems.append(f"commit {short}: {committer_bad}")

    problems.extend(scan_text("pull request title", pr_title or ""))
    problems.extend(scan_text("pull request body", pr_body or ""))

    branch_bad = branch_problem(branch)
    if branch_bad:
        problems.append(branch_bad)

    for problem in problems:
        print(f"::error title=attribution::{problem}")

    if problems:
        print(f"\n{len(problems)} attribution problem(s)", file=sys.stderr)
        return 1
    print(f"{len(commits)} commit(s) in {commit_range} carry no tool attribution")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="check_attribution", description=__doc__.split("\n", 1)[0]
    )
    parser.add_argument("root", nargs="?", default=".", type=Path, help="repository root")
    parser.add_argument(
        "--range",
        dest="commit_range",
        default="origin/main..HEAD",
        help="git log range to scan (default: origin/main..HEAD)",
    )
    args = parser.parse_args(argv)
    return check(
        args.root.resolve(),
        args.commit_range,
        branch=os.environ.get("GITHUB_HEAD_REF"),
        pr_title=os.environ.get("PR_TITLE"),
        pr_body=os.environ.get("PR_BODY"),
    )


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
